import { useEffect, useState, version as reactVersion, type ReactNode } from "react"
import { useRouter } from "@vessel/react-router"
import { ArrowLeft, Settings, UserRound, Palette, Keyboard, RefreshCw, Save, RotateCcw, Cloud, Clock, Download, CheckCircle2, Camera } from "lucide-react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { defaultSettings, type AppSettings, type BackupStatus } from "../../../../shared/settings"
import { applyAppearance } from "./appearance"
import "./settings.css"
const sections = [{ id: "about", label: "关于", icon: UserRound }, { id: "appearance", label: "外观", icon: Palette }, { id: "shortcuts", label: "快捷键", icon: Keyboard }, { id: "sync", label: "同步与备份", icon: RefreshCw }] as const
const fonts = ["Plus Jakarta Sans", "Inter", "system-ui", "PingFang SC", "Georgia"]
const accents = [{ color: "#16a34a", name: "翠绿" }, { color: "#2563eb", name: "海蓝" }, { color: "#7c3aed", name: "紫罗兰" }, { color: "#dc2626", name: "朱红" }, { color: "#d97706", name: "琥珀" }]
function Row({ title, description, children }: { title: string; description?: string; children?: ReactNode }) { return <div className="settings-row"><div className="min-w-0"><h3>{title}</h3>{description && <p>{description}</p>}</div><div className="shrink-0">{children}</div></div> }
export default function SettingsPage() {
  const router = useRouter()
  const [section, setSection] = useState<(typeof sections)[number]["id"]>("about")
  const [draft, setDraft] = useState<AppSettings>(structuredClone(defaultSettings))
  const [saved, setSaved] = useState<AppSettings>()
  const [secret, setSecret] = useState<string | undefined>()
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState("")
  const [status, setStatus] = useState<BackupStatus>({ running: false })
  const [info, setInfo] = useState({ version: "…", electron: "…", node: "…" })
  useEffect(() => { void Promise.all([window.electronAPI.getSettings(), window.electronAPI.getSettingsInfo(), window.electronAPI.getBackupStatus()]).then(([value, version, backup]) => { setDraft(value); setSaved(value); setInfo(version); setStatus(backup) }).catch(error => setError(String(error))) }, [])
  useEffect(() => { if (section !== "sync") return; const timer = setInterval(() => { void window.electronAPI.getBackupStatus().then(setStatus).catch(() => {}) }, 3000); return () => clearInterval(timer) }, [section])
  const dirty = !!saved && (JSON.stringify(saved) !== JSON.stringify(draft) || secret !== undefined)
  const update = <K extends keyof AppSettings>(key: K, value: AppSettings[K]) => setDraft(current => ({ ...current, [key]: value }))
  const backup = <K extends keyof AppSettings["backup"]>(key: K, value: AppSettings["backup"][K]) => setDraft(current => ({ ...current, backup: { ...current.backup, [key]: value } }))
  const run = async (action: () => Promise<void>) => { setBusy(true); setError(""); try { await action() } catch (error) { setError(String(error)) } finally { setBusy(false) } }
  const back = () => { if (dirty && !confirm("有未保存的设置，确定返回吗？")) return; const from = sessionStorage.getItem("vessel-settings-from"); void router.push(from && from !== "/settings" ? from : "/editor") }
  return <div className="vessel-settings flex h-dvh w-full flex-col bg-background text-foreground">
    <header className="flex shrink-0 items-center gap-3 border-b bg-card px-5 py-4"><Button variant="ghost" size="icon" aria-label="返回" title="返回" onClick={back}><ArrowLeft className="size-5" /></Button><div className="rounded-xl border border-green-200 bg-green-50 p-2.5 text-green-600"><Settings className="size-6" /></div><div><h1 className="text-xl font-bold">设置</h1><p className="mt-1 text-xs text-muted-foreground">自定义 Vessel 的外观、行为和功能</p></div><div className="ml-auto flex gap-2"><Button variant="outline" disabled={!saved || busy} onClick={() => { setDraft(structuredClone(defaultSettings)); setSecret("") }}><RotateCcw className="size-4" />重置</Button><Button disabled={!saved || busy || !dirty} className="!bg-green-600 !text-white hover:!bg-green-700" onClick={() => void run(async () => { const next = await window.electronAPI.saveSettings(draft, secret); setDraft(next); setSaved(next); setSecret(undefined); applyAppearance(next); toast.success("设置已保存") })}><Save className="size-4" />保存</Button></div></header>
    <div className="flex min-h-0 flex-1"><nav aria-label="设置分类" className="w-48 shrink-0 border-r bg-card p-3 max-sm:w-32">{sections.map(({ id, label, icon: Icon }) => <button key={id} aria-current={section === id ? "page" : undefined} onClick={() => setSection(id)} className={`mb-1 flex w-full items-center gap-3 rounded-lg px-3 py-3 text-left text-sm ${section === id ? "bg-green-50 font-semibold text-green-600 dark:bg-green-950" : "text-muted-foreground hover:bg-muted"}`}><Icon className="size-4 shrink-0" />{label}</button>)}</nav>
    <main className="min-w-0 flex-1 overflow-auto bg-muted/20 p-6"><div className="mx-auto max-w-[860px]">
      {error && <p role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-600">{error}</p>}
      {!saved && !error && <p role="status">正在读取设置…</p>}
      {section === "about" && <><h2>关于 Vessel</h2><p className="settings-description">应用信息、个人资料和版本详情</p><div className="settings-card flex items-center gap-4 p-6"><label className="relative cursor-pointer"><span className="flex size-16 items-center justify-center overflow-hidden rounded-2xl bg-green-100 text-2xl font-bold text-green-700">{draft.avatar ? <img src={draft.avatar} alt="头像" className="size-full object-cover" /> : draft.name.slice(0, 1)}</span><Camera className="absolute -bottom-1 -right-1 size-6 rounded-full bg-green-600 p-1 text-white" /><input aria-label="更换头像" type="file" accept="image/png,image/jpeg" className="sr-only" onChange={event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 2 * 1024 * 1024) { setError("头像不能超过 2 MB"); return } const reader = new FileReader(); reader.onload = () => update("avatar", String(reader.result)); reader.readAsDataURL(file) }} /></label><div><h3 className="text-lg font-semibold">{draft.name || "本地用户"}</h3><p className="text-xs text-muted-foreground">{draft.email}</p><span className="mt-2 inline-block rounded bg-green-50 px-2 py-1 text-xs text-green-700">本地用户</span></div><span className="ml-auto text-sm text-muted-foreground">v{info.version}</span></div><div className="settings-card"><Row title="用户名" description="本地个人资料"><input aria-label="用户名" value={draft.name} maxLength={80} onChange={e => update("name", e.target.value)} /></Row><Row title="邮箱" description="保存在本机的联系信息"><input aria-label="邮箱" type="email" value={draft.email} onChange={e => update("email", e.target.value)} /></Row></div><div className="settings-card"><Row title="当前版本" description={`Vessel v${info.version}`} /><Row title="Electron" description={info.electron} /><Row title="React" description={reactVersion} /><Row title="Node.js" description={info.node} /></div></>}
      {section === "appearance" && <><h2>外观设置</h2><p className="settings-description">自定义应用的主题、字体和显示大小</p><div className="settings-card"><Row title="主题模式" description="选择应用的明暗主题"><select aria-label="主题模式" value={draft.theme} onChange={e => update("theme", e.target.value as AppSettings["theme"])}><option value="light">浅色</option><option value="dark">深色</option><option value="system">跟随系统</option></select></Row><Row title="界面字体" description="使用本机可用字体，缺失时使用系统字体"><select aria-label="界面字体" value={draft.font} onChange={e => update("font", e.target.value)}>{fonts.map(font => <option key={font}>{font}</option>)}</select></Row><Row title="默认字体大小" description="调整界面大小（12px – 18px）"><div className="flex items-center gap-3"><input aria-label="默认字体大小" type="range" min={12} max={18} value={draft.fontSize} onChange={e => update("fontSize", Number(e.target.value))} /><span className="text-xs">{draft.fontSize}px</span></div></Row><div className="p-5"><h3>强调色</h3><p className="mb-4 text-xs text-muted-foreground">按钮及交互控件的强调颜色</p><div className="grid grid-cols-5 gap-3">{accents.map(({ color, name }) => <button key={color} aria-label={name} aria-pressed={draft.accent === color} className={`rounded-lg border p-3 text-center text-xs ${draft.accent === color ? "ring-2 ring-green-500" : ""}`} onClick={() => update("accent", color)}><span style={{ background: color }} className="mx-auto mb-2 block size-7 rounded-full" />{name}</button>)}</div><div className="mt-4 flex items-center gap-5 rounded-lg bg-muted p-4 text-xs"><span className="text-muted-foreground">预览</span><span className="rounded px-3 py-2 text-white" style={{ background: draft.accent }}>主要按钮</span><span style={{ color: draft.accent }}>文字链接 · 状态标签</span></div></div></div><div className="settings-card p-5"><h3>字体预览</h3><div className="mt-3 rounded-lg bg-muted p-4" style={{ fontFamily: `${draft.font}, sans-serif`, fontSize: draft.fontSize }}><strong>Vessel 笔记应用</strong><p className="mt-2">The quick brown fox jumps over the lazy dog. 本地优先的 Markdown 编辑器。</p></div></div></>}
      {section === "shortcuts" && <><h2>快捷键</h2><p className="settings-description">常用快捷键（编辑操作在对应编辑器中生效）</p><div className="settings-card">{[["保存", "S"], ["页面查找", "F"], ["切换侧边栏", "B"], ["切换开发者工具", "Shift + I"]].map(([label, key]) => <Row key={label} title={label}><kbd className="rounded border bg-muted px-3 py-1 text-xs">{navigator.platform.includes("Mac") ? "⌘" : "Ctrl"} + {key}</kbd></Row>)}</div></>}
      {section === "sync" && <><h2>同步与备份</h2><p className="settings-description">备份已登记工作区文件、应用数据库及配置到 S3；不包含缓存、依赖目录和密钥</p><div className="settings-card p-5"><div className="mb-4 flex gap-3 rounded-xl border border-green-500 bg-green-50 p-4 dark:bg-green-950"><Cloud className="size-8 text-blue-600" /><div><h3>S3 兼容存储</h3><p className="text-xs text-muted-foreground">备份到 AWS S3、MinIO、阿里云 OSS 等 S3 兼容对象存储</p></div></div><div className="grid grid-cols-2 gap-4 rounded-xl border bg-muted/30 p-4">{([["endpoint", "Endpoint（服务端点）", "https://s3.amazonaws.com"], ["accessKey", "Access Key", "AKIA…"], ["bucket", "Bucket 名称", "vessel-backup"], ["region", "区域", "us-east-1"], ["prefix", "路径前缀", "backups/"]] as const).map(([key, label, placeholder]) => <label key={key} className={`text-xs ${["endpoint", "bucket"].includes(key) ? "col-span-2" : ""}`}>{label}<input className="mt-2 !w-full" value={draft.backup[key]} placeholder={placeholder} onChange={e => backup(key, e.target.value)} /></label>)}<label className="col-start-2 row-start-2 text-xs">Secret Key<input className="mt-2 !w-full" type="password" autoComplete="new-password" placeholder={draft.backup.hasSecret ? "已保存（留空保持不变）" : "输入 Secret Key"} value={secret ?? ""} onChange={e => setSecret(e.target.value || undefined)} /></label><div className="col-span-2"><Button variant="outline" disabled={busy || !saved} onClick={() => void run(async () => { await window.electronAPI.testBackup(draft.backup, secret); toast.success("连接成功，存储桶可访问") })}>测试连接</Button></div></div></div><div className="settings-card"><Row title="自动备份" description="应用运行期间定期备份到已配置的 S3 存储"><Switch aria-label="自动备份" checked={draft.backup.automatic} onCheckedChange={value => backup("automatic", value)} /></Row><div className="p-5"><label className="block rounded-xl border bg-muted/30 p-4 text-xs"><span className="mb-3 flex items-center gap-2 text-muted-foreground"><Clock className="size-4" />更新频率</span><select className="!w-full" aria-label="更新频率" value={draft.backup.minutes} onChange={e => backup("minutes", Number(e.target.value) as 5 | 10 | 30)}>{[5, 10, 30].map(value => <option key={value} value={value}>{value} 分钟</option>)}</select></label><div className="mt-4 flex items-center gap-3 rounded-xl border p-4"><CheckCircle2 className={`size-6 ${status.time && !status.error ? "text-green-600" : "text-muted-foreground"}`} /><div className="min-w-0 flex-1"><h3>{status.running ? "正在备份…" : status.error ? "上次备份失败" : status.time ? "上次备份成功" : "尚未执行备份"}</h3><p className="break-all text-xs text-muted-foreground">{status.error || (status.time ? `${new Date(status.time).toLocaleString()} · ${((status.size || 0) / 1024).toFixed(1)} KB · S3` : "先保存存储配置，再执行备份")}</p></div><Button variant="outline" disabled={busy || status.running || dirty || !saved} onClick={() => void run(async () => { setStatus(await window.electronAPI.runBackup()) })}><Download className="size-4" />立即备份</Button></div></div></div></>}
    </div></main></div>
  </div>
}
