import { useEffect, useRef, useState, type PointerEvent, type ReactNode } from 'react'
import { ImageIcon, Upload, Clipboard, Download, ScanLine, Expand, Crop, RotateCw, Sparkles, Minimize2, Type, Shield, Palette, Layers, ZoomIn, ZoomOut, Maximize, PanelLeft, PanelRight, Copy, Undo2, LoaderCircle } from 'lucide-react'
import { ScrollArea, ScrollBar } from '@/components/ui/scroll-area'
import { Switch } from '@/components/ui/switch'
import { recognizeImage } from '@/lib/image-ocr'
import { toast } from 'sonner'
import { canvasFor, loadImage, imageCanvas, cropImage, clampRegion, downloadImage, downloadText, type ImageRegion } from './image-operations'
import './image-toolbox.css'
const groups = [
  { label: '基础编辑', tools: [{ id: 'resize', title: '缩放', icon: Expand }, { id: 'crop', title: '裁剪', icon: Crop }, { id: 'rotate', title: '旋转', icon: RotateCw }] },
  { label: '画质优化', tools: [{ id: 'sharpen', title: '锐化', icon: Sparkles }, { id: 'compress', title: '压缩', icon: Minimize2 }] },
  { label: '导出转换', tools: [{ id: 'convert', title: '格式转换', icon: Type }] },
  { label: '高级功能', tools: [{ id: 'watermark', title: '加水印', icon: Shield }, { id: 'color', title: '取主色调', icon: Palette }, { id: 'composite', title: '合成', icon: Layers }] },
  { label: '文字识别', tools: [{ id: 'ocr', title: 'OCR 识别', icon: ScanLine }] }
]
const allTools = groups.flatMap(g => g.tools)
const copy = (value: string) => void navigator.clipboard.writeText(value).then(() => toast.success('已复制')).catch(e => toast.error(String(e)))
function NumberField({ label, value, onChange, min = 0, max = 8192 }: { label: string; value: number; onChange: (v: number) => void; min?: number; max?: number }) {
  return <label className="image-field">{label}<input type="number" min={min} max={max} value={value} onChange={e => onChange(Number(e.target.value))} /></label>
}
function RangeField({ label, value, onChange, max = 100 }: { label: string; value: number; onChange: (v: number) => void; max?: number }) {
  return <label className="image-field">{label}<span className="image-range"><input type="range" min="0" max={max} value={value} onChange={e => onChange(Number(e.target.value))} /><output>{value}</output></span></label>
}
function Action({ children, onClick, disabled }: { children: ReactNode; onClick: () => void; disabled?: boolean }) { return <button className="image-button image-primary" disabled={disabled} onClick={onClick}>{children}</button> }
export function ImageToolbox() {
  const [image, setImage] = useState(''), [history, setHistory] = useState<string[]>([]), [tool, setTool] = useState('ocr')
  const [size, setSize] = useState({ width: 1, height: 1 }), [resize, setResize] = useState({ width: 1, height: 1 })
  const [region, setRegion] = useState<ImageRegion>({ x: 0, y: 0, width: 1, height: 1 }), [regionOCR, setRegionOCR] = useState(false)
  const [busy, setBusy] = useState(false), [result, setResult] = useState(''), [elapsed, setElapsed] = useState(0)
  const [zoom, setZoom] = useState(1), [nav, setNav] = useState(true), [settings, setSettings] = useState(true)
  const [viewport, setViewport] = useState<HTMLDivElement | null>(null), [bounds, setBounds] = useState({ width: 600, height: 600 })
  const [locked, setLocked] = useState(true), [quality, setQuality] = useState(85), [format, setFormat] = useState('image/png')
  const [angle, setAngle] = useState(90), [strength, setStrength] = useState(50), [watermark, setWatermark] = useState('Vessel')
  const [fontSize, setFontSize] = useState(32), [opacity, setOpacity] = useState(65), [ink, setInk] = useState('#ffffff'), [colors, setColors] = useState<string[]>([])
  const [layer, setLayer] = useState(''), [layerX, setLayerX] = useState(0), [layerY, setLayerY] = useState(0), [layerWidth, setLayerWidth] = useState(200)
  const [blend, setBlend] = useState<GlobalCompositeOperation>('source-over')
  const fileInput = useRef<HTMLInputElement>(null), layerInput = useRef<HTMLInputElement>(null), root = useRef<HTMLDivElement>(null)
  const drag = useRef<{ x: number; y: number } | null>(null)
  useEffect(() => {
    if (!viewport) return
    const observer = new ResizeObserver(([entry]) => setBounds({ width: entry.contentRect.width, height: entry.contentRect.height }))
    observer.observe(viewport); return () => observer.disconnect()
  }, [viewport])
  const fit = Math.min(1, Math.max(1, bounds.width - 48) / size.width, Math.max(1, bounds.height - 48) / size.height)
  const scale = fit * zoom, selection = !!image && (tool === 'crop' || (tool === 'ocr' && regionOCR))
  const active = allTools.find(t => t.id === tool)!, Icon = active.icon
  const run = async (fn: () => Promise<void>) => { if (busy) return; setBusy(true); try { await fn() } catch (e) { toast.error(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  const accept = async (src: string, reset = false) => {
    const img = await loadImage(src), next = { width: img.naturalWidth, height: img.naturalHeight }
    setHistory(previous => reset ? [] : [...previous.slice(-2), image].filter(Boolean)); setImage(src); setSize(next); setResize(next); setRegion({ x: 0, y: 0, ...next }); setZoom(1); setResult(''); setElapsed(0); setColors([])
    if (reset) { setLayer(''); setFormat('image/png') }
  }
  const apply = (operation: () => Promise<HTMLCanvasElement>, mime = 'image/png') => void run(async () => { const canvas = await operation(); await accept(canvas.toDataURL(mime, quality / 100)) })
  const readFile = async (file: File, isLayer: boolean) => {
    if (!/^image\/(png|jpeg|webp)$/.test(file.type) || file.size > 30_000_000) throw new Error('请选择 30 MB 以内的 PNG、JPEG 或 WebP 图片')
    const src = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('读取图片失败')); reader.readAsDataURL(file) })
    if (isLayer) { const img = await loadImage(src); setLayer(src); setLayerWidth(Math.min(size.width, img.naturalWidth)) } else await accept(src, true)
  }
  const paste = () => void run(async () => { const src = await window.electronAPI.readClipboardImage(); if (!src) throw new Error('剪贴板中没有图片'); await accept(src, true) })
  const exportCurrent = () => void run(async () => { const canvas = await imageCanvas(image); if (format === 'image/jpeg') { const ctx = canvas.getContext('2d')!; ctx.globalCompositeOperation = 'destination-over'; ctx.fillStyle = '#fff'; ctx.fillRect(0, 0, canvas.width, canvas.height) } downloadImage(canvas.toDataURL(format, quality / 100), `vessel-image.${format.split('/')[1]}`) })
  const rotate = (degrees: number, flip?: 'x' | 'y') => apply(async () => {
    const img = await loadImage(image), radians = degrees * Math.PI / 180
    const w = img.naturalWidth, h = img.naturalHeight
    const canvas = canvasFor(Math.ceil(Math.abs(w * Math.cos(radians)) + Math.abs(h * Math.sin(radians)) - 1e-8), Math.ceil(Math.abs(w * Math.sin(radians)) + Math.abs(h * Math.cos(radians)) - 1e-8))
    const ctx = canvas.getContext('2d')!; ctx.translate(canvas.width / 2, canvas.height / 2); ctx.rotate(radians); ctx.scale(flip === 'x' ? -1 : 1, flip === 'y' ? -1 : 1); ctx.drawImage(img, -w / 2, -h / 2); return canvas
  })
  const point = (e: PointerEvent<HTMLDivElement>) => { const box = e.currentTarget.getBoundingClientRect(); return { x: Math.max(0, Math.min(size.width, (e.clientX - box.left) / scale)), y: Math.max(0, Math.min(size.height, (e.clientY - box.top) / scale)) } }
  const move = (e: PointerEvent<HTMLDivElement>) => { if (!drag.current) return; const p = point(e), start = drag.current; setRegion(clampRegion({ x: Math.min(start.x, p.x), y: Math.min(start.y, p.y), width: Math.abs(p.x - start.x), height: Math.abs(p.y - start.y) }, size)) }
  const recognize = () => void run(async () => { const started = performance.now(); const src = regionOCR ? (await cropImage(image, region)).toDataURL() : (await imageCanvas(image)).toDataURL(); const text = await recognizeImage(src); setResult(text); setElapsed((performance.now() - started) / 1000); if (!text) toast.info('未识别到文字') })
  const resizeField = (axis: 'width' | 'height', value: number) => setResize(current => ({ ...current, [axis]: value, ...(locked ? axis === 'width' ? { height: Math.round(value * size.height / size.width) } : { width: Math.round(value * size.width / size.height) } : {}) }))
  const cropField = (axis: keyof ImageRegion, value: number) => setRegion(current => clampRegion({ ...current, [axis]: value }, size))
  const disabled = !image || busy
  return <div className="image-toolbox" ref={root} aria-busy={busy}>
    <header className="image-header"><span className="image-brand"><ImageIcon /></span><div><h1>图片工具箱</h1><p>缩放 · 裁剪 · 旋转 · 压缩 · 转换 · 水印 · 取色 · 锐化 · 合成 · OCR</p></div><div className="image-header-actions"><button className="image-button" disabled={busy} onClick={() => fileInput.current?.click()}><Upload />导入图片</button><button className="image-button" disabled={busy} onClick={paste}><Clipboard />剪贴板</button><Action disabled={disabled} onClick={exportCurrent}><Download />导出</Action></div></header>
    {[false, true].map(isLayer => <input key={String(isLayer)} ref={isLayer ? layerInput : fileInput} hidden type="file" accept="image/png,image/jpeg,image/webp" aria-label={isLayer ? '添加合成图片' : '导入图片文件'} onChange={e => { const file = e.target.files?.[0]; e.target.value = ''; if (file) void run(() => readFile(file, isLayer)) }} />)}
    <div className="image-body">
      {nav && <ScrollArea className="image-tool-nav"><nav aria-label="图片操作">{groups.map(group => <section key={group.label}><h3>{group.label}</h3>{group.tools.map(({ id, title, icon: ToolIcon }) => <button key={id} aria-pressed={tool === id} onClick={() => setTool(id)}><ToolIcon />{title}</button>)}</section>)}</nav></ScrollArea>}
      <section className="image-preview-area"><div className="image-preview-toolbar"><button aria-label="缩小图片" disabled={!image || zoom <= 0.25} onClick={() => setZoom(z => Math.max(.25, z - .25))}><ZoomOut /></button><output>{Math.round(scale * 100)}%</output><button aria-label="放大图片" disabled={!image || zoom >= 4} onClick={() => setZoom(z => Math.min(4, z + .25))}><ZoomIn /></button><button aria-label="图片适应画布" onClick={() => setZoom(1)}><Expand /></button><button aria-label="撤销图片编辑" disabled={busy || !history.length} onClick={() => { const previous = history.at(-1)!; const remaining = history.slice(0, -1); void run(async () => { await accept(previous); setHistory(remaining) }) }}><Undo2 /></button><span className="image-toolbar-spacer" /><button aria-label="切换图片工具栏" aria-pressed={nav} onClick={() => setNav(v => !v)}><PanelLeft /></button><button aria-label="切换图片设置面板" aria-pressed={settings} onClick={() => setSettings(v => !v)}><PanelRight /></button><button aria-label="全屏预览" onClick={() => void (document.fullscreenElement ? document.exitFullscreen() : root.current?.requestFullscreen())?.catch(e => toast.error(String(e)))}><Maximize /></button></div>
        <div ref={setViewport} className="image-viewport"><ScrollArea className="image-preview-scroll"><div className="image-stage" style={{ width: Math.max(bounds.width, size.width * scale + 48), height: Math.max(bounds.height, size.height * scale + 48) }}>
          {image ? <div className={'image-picture' + (selection ? ' selecting' : '')} style={{ width: size.width * scale, height: size.height * scale }} onPointerDown={e => { if (!selection || busy) return; e.currentTarget.setPointerCapture(e.pointerId); drag.current = point(e); move(e) }} onPointerMove={move} onPointerUp={e => { move(e); drag.current = null }} onPointerCancel={() => { drag.current = null }}><img src={image} alt="待处理图片" draggable={false} />{selection && <div className="image-crop" style={{ left: region.x * scale, top: region.y * scale, width: region.width * scale, height: region.height * scale }}><i /><i /><i /><i /></div>}</div> : <button className="image-empty" onClick={() => fileInput.current?.click()}><ImageIcon /><strong>导入图片开始编辑</strong><span>PNG、JPEG、WebP · 本地处理</span></button>}
        </div><ScrollBar orientation="horizontal" /></ScrollArea>{busy && <div className="image-processing" role="status"><LoaderCircle className="animate-spin" />{tool === 'ocr' ? '正在识别，请稍候…' : '正在处理图片…'}</div>}</div>
        {image && <div className="image-size">{size.width} × {size.height} px{selection && <span>拖动框选区域 · {region.width} × {region.height} px</span>}</div>}
      </section>
      {settings && <aside className="image-settings"><div className="image-settings-heading"><span><Icon /></span><div><h2>{active.title}</h2><p>{tool === 'ocr' ? '图片文字提取，本地离线识别' : '调整参数后应用到图片'}</p></div></div><ScrollArea className="image-settings-scroll"><div className="image-settings-content"><fieldset disabled={busy}>
        {tool === 'ocr' && <><div className="image-control-row"><span className="image-language">中文 + 英文</span><Action disabled={disabled} onClick={recognize}><Sparkles />开始识别</Action></div><label className="image-switch">框选区域识别<Switch checked={regionOCR} onCheckedChange={setRegionOCR} /></label><div className="image-result-label">识别结果<div><button aria-label="复制识别文字" disabled={!result} onClick={() => copy(result)}><Copy /></button><button aria-label="下载识别文字" disabled={!result} onClick={() => downloadText(result, 'ocr-result.txt')}><Download /></button></div></div><textarea aria-label="识别结果" value={result} onChange={e => setResult(e.target.value)} placeholder="点击开始识别，结果将显示在这里" className="image-result" /><div className="image-result-stats">{result ? result.split('\n').length : 0} 行 · {result.length} 字 <span>耗时 {elapsed.toFixed(1)}s</span> · 本地离线</div></>}
        {tool === 'resize' && <><div className="image-control-row"><NumberField label="宽度 (px)" min={1} value={resize.width} onChange={v => resizeField('width', v)} /><NumberField label="高度 (px)" min={1} value={resize.height} onChange={v => resizeField('height', v)} /></div><label className="image-switch">锁定比例<Switch checked={locked} onCheckedChange={setLocked} /></label><div className="image-presets">{[25, 50, 75, 100, 200].map(v => <button key={v} onClick={() => setResize({ width: Math.round(size.width * v / 100), height: Math.round(size.height * v / 100) })}>{v}%</button>)}</div><Action disabled={disabled} onClick={() => apply(async () => { const img = await loadImage(image), canvas = canvasFor(resize.width, resize.height), ctx = canvas.getContext('2d')!; ctx.imageSmoothingQuality = 'high'; ctx.drawImage(img, 0, 0, canvas.width, canvas.height); return canvas })}>应用缩放</Action></>}
        {tool === 'crop' && <><p className="image-hint">在图片上拖动框选，或输入裁剪范围。</p><div className="image-control-row"><NumberField label="X" value={region.x} onChange={v => cropField('x', v)} /><NumberField label="Y" value={region.y} onChange={v => cropField('y', v)} /></div><div className="image-control-row"><NumberField label="宽度" min={1} value={region.width} onChange={v => cropField('width', v)} /><NumberField label="高度" min={1} value={region.height} onChange={v => cropField('height', v)} /></div><div className="image-presets">{[1, 4 / 3, 16 / 9, 9 / 16].map((ratio, i) => <button key={ratio} onClick={() => { const w = Math.min(size.width, size.height * ratio), h = w / ratio; setRegion(clampRegion({ x: (size.width - w) / 2, y: (size.height - h) / 2, width: w, height: h }, size)) }}>{['1:1', '4:3', '16:9', '9:16'][i]}</button>)}</div><div className="image-control-row"><button className="image-button" onClick={() => setRegion({ x: 0, y: 0, ...size })}>重置</button><Action disabled={disabled} onClick={() => apply(() => cropImage(image, region))}>应用裁剪</Action></div></>}
        {tool === 'rotate' && <><div className="image-presets"><button disabled={disabled} onClick={() => rotate(-90)}>左转 90°</button><button disabled={disabled} onClick={() => rotate(90)}>右转 90°</button><button disabled={disabled} onClick={() => rotate(0, 'x')}>水平翻转</button><button disabled={disabled} onClick={() => rotate(0, 'y')}>垂直翻转</button></div><NumberField label="旋转角度" min={-360} max={360} value={angle} onChange={setAngle} /><Action disabled={disabled} onClick={() => rotate(angle)}>应用旋转</Action></>}
        {tool === 'sharpen' && <><RangeField label="锐化强度" value={strength} onChange={setStrength} /><Action disabled={disabled} onClick={() => apply(async () => { const canvas = await imageCanvas(image), ctx = canvas.getContext('2d')!, data = ctx.getImageData(0, 0, canvas.width, canvas.height), original = new Uint8ClampedArray(data.data), w = canvas.width, h = canvas.height, amount = strength / 100; for (let y = 1; y < h - 1; y++) for (let x = 1; x < w - 1; x++) for (let c = 0; c < 3; c++) { const i = (y * w + x) * 4 + c; data.data[i] = original[i] + amount * (4 * original[i] - original[i - 4] - original[i + 4] - original[i - w * 4] - original[i + w * 4]) } ctx.putImageData(data, 0, 0); return canvas })}>应用锐化</Action></>}
        {(tool === 'compress' || tool === 'convert') && <><label className="image-field">导出格式<select value={format} onChange={e => setFormat(e.target.value)}><option value="image/png">PNG（无损）</option><option value="image/jpeg">JPEG</option><option value="image/webp">WebP</option></select></label>{format !== 'image/png' && <RangeField label="图片质量 (%)" value={quality} onChange={setQuality} />}<p className="image-hint">PNG 保留透明度；JPEG 使用白色背景。压缩大小由图片内容和质量决定。</p><Action disabled={disabled} onClick={exportCurrent}><Download />导出图片</Action></>}
        {tool === 'watermark' && <><label className="image-field">水印文字<input value={watermark} onChange={e => setWatermark(e.target.value)} maxLength={200} /></label><NumberField label="字号 (px)" min={1} max={500} value={fontSize} onChange={setFontSize} /><RangeField label="不透明度 (%)" value={opacity} onChange={setOpacity} /><label className="image-field">文字颜色<input type="color" value={ink} onChange={e => setInk(e.target.value)} /></label><p className="image-hint">文字放置在图片右下角。</p><Action disabled={disabled || !watermark} onClick={() => apply(async () => { const canvas = await imageCanvas(image), ctx = canvas.getContext('2d')!; ctx.globalAlpha = opacity / 100; ctx.fillStyle = ink; ctx.font = `${Math.max(1, Math.min(500, fontSize))}px sans-serif`; ctx.textAlign = 'right'; ctx.textBaseline = 'bottom'; ctx.fillText(watermark, canvas.width - Math.min(24, canvas.width * .05), canvas.height - Math.min(24, canvas.height * .05), canvas.width * .9); return canvas })}>添加水印</Action></>}
        {tool === 'color' && <><Action disabled={disabled} onClick={() => void run(async () => { const img = await loadImage(image), canvas = canvasFor(128, 128), ctx = canvas.getContext('2d')!; ctx.drawImage(img, 0, 0, 128, 128); const { data } = ctx.getImageData(0, 0, 128, 128), counts = new Map<string, number>(); for (let i = 0; i < data.length; i += 4) { if (data[i + 3] < 128) continue; const hex = '#' + [data[i], data[i + 1], data[i + 2]].map(v => Math.min(255, Math.round(v / 32) * 32).toString(16).padStart(2, '0')).join(''); counts.set(hex, (counts.get(hex) || 0) + 1) } setColors([...counts].sort((a, b) => b[1] - a[1]).slice(0, 6).map(([hex]) => hex)) })}>提取主色调</Action><div className="image-swatches">{colors.map(color => <button key={color} onClick={() => copy(color)}><span style={{ background: color }} />{color}</button>)}</div>{!!colors.length && <button className="image-button" onClick={() => copy(colors.map((c, i) => `--image-color-${i + 1}: ${c};`).join('\n'))}><Copy />复制 CSS 变量</button>}</>}
        {tool === 'composite' && <><button className="image-button" disabled={disabled} onClick={() => layerInput.current?.click()}><Upload />添加图片图层</button>{layer && <img src={layer} alt="待合成图层" className="image-layer-thumbnail" />}<div className="image-control-row"><NumberField label="X" min={-8192} value={layerX} onChange={setLayerX} /><NumberField label="Y" min={-8192} value={layerY} onChange={setLayerY} /></div><NumberField label="图层宽度 (px)" min={1} value={layerWidth} onChange={setLayerWidth} /><RangeField label="不透明度 (%)" value={opacity} onChange={setOpacity} /><label className="image-field">混合模式<select value={blend} onChange={e => setBlend(e.target.value as GlobalCompositeOperation)}><option value="source-over">正常</option><option value="multiply">正片叠底</option><option value="screen">滤色</option><option value="overlay">叠加</option></select></label><Action disabled={disabled || !layer} onClick={() => apply(async () => { const canvas = await imageCanvas(image), img = await loadImage(layer), ctx = canvas.getContext('2d')!; if (layerWidth < 1 || layerWidth > 8192) throw new Error('图层宽度须在 1–8192 像素内'); ctx.globalAlpha = opacity / 100; ctx.globalCompositeOperation = blend; ctx.drawImage(img, layerX, layerY, layerWidth, layerWidth * img.naturalHeight / img.naturalWidth); return canvas })}>合并图层</Action></>}
      </fieldset></div></ScrollArea>{tool === 'ocr' && <footer className="image-settings-footer"><button className="image-button" disabled={busy || !result} onClick={() => { setResult(''); setElapsed(0) }}>清空</button><Action disabled={!result} onClick={() => copy(result)}>复制全部</Action></footer>}</aside>}
    </div>
  </div>
}
