import { expect, it } from "vitest"
import { BrowserHistory } from "../../src/main/browser-history"
it("keeps only 30 days, preserves visits and deletes chosen records", () => {
  const history = new BrowserHistory(":memory:")
  const now = Date.now()
  history.add('https://old.test', 'old', now - 31 * 86400000)
  const id = history.add('https://current.test', 'current', now)!
  history.add('file:///secret', 'not a website')
  expect(history.list()).toHaveLength(1)
  history.title(id, 'new title')
  expect(history.list()[0].title).toBe('new title')
  history.favicon(id, 'https://current.test/icon.png')
  expect(history.list()[0].favicon).toBe('https://current.test/icon.png')
  history.favicon(id, 'file:///secret')
  expect(history.list()[0].favicon).toBe('https://current.test/icon.png')
  history.delete(id)
  expect(history.list()).toEqual([])
  history.add('https://current.test', 'current')
  history.delete(null)
  expect(history.list()).toEqual([])
  history.close()
})
it("omits tracking redirects and coalesces quick duplicate navigations while keeping later visits", () => {
  const history = new BrowserHistory(':memory:')
  const now = Date.now()
  expect(history.add('https://www.bing.com/ck/a?tracking=1', 'redirect', now)).toBeUndefined()
  const first = history.add('https://uviewui.com/components/intro', '介绍', now)
  expect(history.add('https://uviewui.com/components/intro.html', '介绍', now + 1000)).toBe(first)
  expect(history.add('https://uviewui.com/components/intro.html#section', '介绍', now + 2000)).toBe(first)
  expect(history.list()).toHaveLength(1)
  history.add('https://uviewui.com/components/intro.html', '介绍', now + 120000)
  expect(history.list()).toHaveLength(2)
  history.close()
})
it('stores bookmarks without fabricating visits and preserves bookmarks when clearing history', () => {
  const history = new BrowserHistory(':memory:')
  history.setBookmarks([{ url: 'https://saved.test/', title: 'Saved' }])
  expect(history.list()).toEqual([])
  history.add('https://saved.test/', 'Saved')
  expect(history.list()[0].bookmarked).toBe(1)
  history.delete(null)
  history.add('https://saved.test/', 'Saved again')
  expect(history.list()[0].bookmarked).toBe(1)
  history.setBookmarks([])
  expect(history.list()[0].bookmarked).toBe(0)
  history.close()
})
