import { ScrollArea } from "@/components/ui/scroll-area"
import { useRef, useEffect, useState, type ReactNode } from "react"
import { Globe, Plus, X } from "lucide-react"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem } from "@/components/ui/dropdown-menu"
type PreviewTab = { id: string; title: string; active?: boolean; url?: string; favicon?: string }
export function TabSwitcher({ children, tabs, onSelect, side = "bottom", preview = false, onNew, onClose }: { children: ReactNode; tabs: PreviewTab[]; onSelect: (id: string) => void; side?: "bottom" | "right"; preview?: boolean; onNew?: () => void; onClose?: (id: string) => void }) {
  const [open, setOpen] = useState(false)
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined)
  const enter = () => { clearTimeout(timer.current); setOpen(tabs.length > 0) }
  const leave = () => { timer.current = setTimeout(() => setOpen(false), 180) }
  useEffect(() => () => clearTimeout(timer.current), [])
  if (!tabs.length) return <>{children}</>
  return <DropdownMenu modal={false} open={open} onOpenChange={setOpen}><DropdownMenuTrigger asChild><span className={`inline-flex shrink-0 ${open && !preview ? '[&_button]:!bg-emerald-700 [&_button]:!text-white [&_svg]:!text-white' : ''}`} onMouseEnter={enter} onMouseLeave={leave} onFocus={enter}>{children}</span></DropdownMenuTrigger><DropdownMenuContent side={side} align="start" onCloseAutoFocus={e => e.preventDefault()} onMouseEnter={enter} onMouseLeave={leave} className={preview ? "z-[70] w-[280px] overflow-hidden rounded-xl border-stone-200 bg-white p-0 shadow-xl" : "z-[70] w-64 p-1"}>
    {preview ? <div className="flex items-center gap-2 border-b border-stone-100 bg-[#faf9f7] px-3 py-2.5"><span className="flex size-6 items-center justify-center rounded-md bg-emerald-50 text-green-600"><Globe size={13} /></span><span className="text-xs font-semibold">已打开标签页</span><span className="rounded-full bg-green-600 px-1.5 text-[10px] font-semibold text-white">{tabs.length}</span><button aria-label="新建浏览器标签页" className="ml-auto flex size-6 items-center justify-center rounded-md text-stone-500 hover:bg-stone-200" onClick={() => { onNew?.(); setOpen(false) }}><Plus size={14} /></button></div> : <div className="px-2 py-2 text-xs text-stone-400">已打开 {tabs.length} 个标签页</div>}
    <ScrollArea className={`max-h-[min(18rem,60vh)] [&_[data-radix-scroll-area-viewport]]:max-h-[min(18rem,60vh)] ${preview ? 'p-1' : ''}`}>{tabs.map(tab => <div key={tab.id} className="group relative"><DropdownMenuItem onSelect={() => { onSelect(tab.id); setOpen(false) }} className={`relative w-full rounded-md px-3 py-2 text-left text-xs focus:!bg-[#f0efed] focus:!text-stone-700 data-[highlighted]:!bg-[#f0efed] data-[highlighted]:!text-stone-700 ${tab.active ? `${preview ? 'bg-emerald-50' : ''} text-green-700` : 'text-stone-700'} ${preview ? 'gap-3 pr-8' : ''}`} title={tab.title}>
      {preview && <>{tab.active && <span className="absolute left-0 top-3 bottom-3 w-[3px] rounded-r bg-green-600" />}<span className="flex size-5 shrink-0 items-center justify-center">{tab.favicon ? <img src={tab.favicon} alt="" className="size-4 object-contain" onError={e => { e.currentTarget.style.display = 'none' }} /> : <Globe size={15} />}</span></>}
      <span className="min-w-0 flex-1"><span className={`block truncate ${preview ? 'font-semibold' : ''}`}>{tab.title}</span>{preview && <span className="mt-0.5 block truncate text-[11px] font-normal tracking-wide text-stone-400">{tab.url?.replace(/^https?:\/\//, '').replace(/\/$/, '')}</span>}</span>
    </DropdownMenuItem>{preview && onClose && <button aria-label={`关闭 ${tab.title}`} onClick={e => { e.stopPropagation(); onClose(tab.id) }} className="absolute right-2 top-1/2 flex size-5 -translate-y-1/2 items-center justify-center rounded text-stone-400 opacity-0 hover:bg-stone-200 hover:text-stone-700 focus:opacity-100 group-hover:opacity-100 group-focus-within:opacity-100"><X size={13} /></button>}</div>)}</ScrollArea>
  </DropdownMenuContent></DropdownMenu>
}
