const { app, BrowserWindow, session } = require('electron')
const ts = require('typescript')
const { mkdtempSync, readFileSync, writeFileSync } = require('node:fs')
const { tmpdir } = require('node:os')
const { join } = require('node:path')
const assert = require('node:assert/strict')
const directory = mkdtempSync(join(tmpdir(), 'vessel-igg-'))
app.setPath('userData', directory)
writeFileSync(join(directory, 'compat.cjs'), ts.transpileModule(readFileSync(join(__dirname, '../src/main/browser-site-compatibility.ts'), 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText)
const { registerBrowserSiteCompatibility } = require(join(directory, 'compat.cjs'))
app.whenReady().then(async () => {
  const browserSession = session.fromPartition('igg-smoke')
  const requests = []
  browserSession.webRequest.onCompleted(details => {
    if (["script", "stylesheet"].includes(details.resourceType)) requests.push({ url: details.url, status: details.statusCode })
  })
  registerBrowserSiteCompatibility(browserSession)
  const window = new BrowserWindow({ show: false, webPreferences: { session: browserSession, sandbox: true, contextIsolation: true, nodeIntegration: false, webSecurity: true, allowRunningInsecureContent: false } })
  await window.loadURL('https://iguge.xyz/helper/?page_id=210')
  console.log(JSON.stringify(requests, null, 2))
  assert(requests.some(item => item.url.startsWith('https://igghelper.com/helper/') && item.url.includes('wp-embed.min.js') && item.status === 200))
  assert(requests.some(item => item.url.startsWith('https://igghelper.com/helper/') && item.url.includes('.css') && item.status === 200))
  assert(!requests.some(item => item.url.startsWith('http://')))
  console.log('PASS: live iGuge scripts and styles loaded over HTTPS with webSecurity enabled')
  window.destroy()
  app.exit(0)
}).catch(error => { console.error(error); app.exit(1) })
setTimeout(() => { console.error('Timed out'); app.exit(1) }, 45000).unref()
