const {app,BrowserWindow,ipcMain}=require('electron')
const {mkdtempSync}=require('node:fs'),{tmpdir}=require('node:os'),{join,resolve}=require('node:path')
app.setPath('userData',mkdtempSync(join(tmpdir(),'vessel-startup-')))
app.whenReady().then(async()=>{
 for(const [channel,value] of Object.entries({'settings:get':{theme:'light',font:'Plus Jakarta Sans',fontSize:14,accent:'#16a34a'},'markdown:pending':[],'app-state:get':null,'app-state:set':null,'browser:extensions:list':[]}))ipcMain.handle(channel,()=>value)
 const win=new BrowserWindow({show:false,webPreferences:{preload:resolve('out/preload/index.js'),sandbox:false,contextIsolation:true,nodeIntegration:true,webviewTag:true}})
 win.webContents.on('console-message',(_event,level,message)=>console.log('CONSOLE',level,message))
 win.webContents.on('did-fail-load',(_e,code,message,url)=>console.log('LOAD FAILED',code,message,url))
 await win.loadURL('http://localhost:5173')
 await new Promise(r=>setTimeout(r,5000))
 const text=await win.webContents.executeJavaScript('document.body.innerText.trim()')
 if(!text)throw new Error('Development renderer is blank')
 console.log('PASS development startup:',text.slice(0,250))
 win.destroy();app.quit()
}).catch(e=>{console.error(e);app.exit(1)})
